board:
  config: # 체스판 설정
    square:
      row_count: 8
      column_count: 8
      width: 3
      height: 3
      black_block: STRIPPED_DARK_OAK_WOOD
      white_block: STRIPPED_PALE_OAK_WOOD
    inner_border:
      thickness: 1
      block: STRIPPED_OAK_WOOD
    frame:
      thickness: 2
      block: DARK_OAK_WOOD

  generated: # 생성된 체스판 정보
    bounding_box:
      min:
        x:
        y:
        z:
      max:
        x:
        y:
        z:
    a1:
      x:
      y:
      z:
    square:
      row_count:
      column_count:
      width:
      height:
    inner_border_thickness:
    frame_thickness:
