# ChessWar 플러그인 초기 설정 파일
# 이 파일의 값들은 플러그인에서 사용되는 초기 설정값입니다.
# data.yml 파일의 *.config 섹션에서 개별적으로 덮어쓸 수 있습니다.

board:
  config:
    square:
      row-count: 8
      col-count: 8
      width: 3
      height: 3
      black-block: STRIPPED_DARK_OAK_WOOD
      white-block: STRIPPED_PALE_OAK_WOOD
    inner-border:
      thickness: 1
      block: STRIPPED_OAK_WOOD
    frame:
      thickness: 2
      block: DARK_OAK_WOOD
