name: ChessWar
version: ${version}
main: dev.tecte.chessWar.ChessWar
api-version: '1.21'
logging:
  prefix: "[ChessWar]"
commands:
  chesswar:
    aliases: [cw]
    description: ChessWar plugin commands
    usage: /chesswar [subcommand]
